/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/*
import com.itextpdf.io.font.FontConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import static com.itextpdf.kernel.pdf.PdfName.Font;
import static com.itextpdf.kernel.pdf.PdfName.FontFamily;


import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.border.Border;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Text;*/
import com.sun.javafx.geom.Rectangle;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.InputMismatchException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Desktop;
//import sun.text.normalizer.RangeValueIterator.Element;

import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import parqueadero_proyecto.*;

/*
 *
 * @author Principal
 */
public class PanelIngresarVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form PanelIngresarVehiculo
     */
    public PanelIngresarVehiculo() {
        initComponents();
        

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tfPropietario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbMoto = new javax.swing.JRadioButton();
        rbAuto = new javax.swing.JRadioButton();
        button1 = new java.awt.Button();
        tfPropietario1 = new javax.swing.JTextField();
        tfPlaca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Modulo de Ingreso de vehiculos al parqueadero");

        tfPropietario.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        tfPropietario.setToolTipText("Nombre");
        tfPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPropietarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Placa Motocicleta");

        jLabel3.setText("Nombre propietario");

        jLabel4.setText("Tipo de vehiculo");

        buttonGroup1.add(rbMoto);
        rbMoto.setSelected(true);
        rbMoto.setText("Motocicleta");
        rbMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMotoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbAuto);
        rbAuto.setText("Automovil");
        rbAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAutoActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(255, 51, 0));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Registrar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        tfPropietario1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        tfPropietario1.setToolTipText("Nombre");
        tfPropietario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPropietario1ActionPerformed(evt);
            }
        });

        tfPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPlacaActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbMoto)
                        .addGap(57, 57, 57)
                        .addComponent(rbAuto))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPropietario1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPropietario1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAuto)
                    .addComponent(rbMoto))
                .addGap(26, 26, 26)
                .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    String fechaHora = "";
    String hora = "";
    String fecha = "";
     
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        
        
        //Hora de entrada
                DateFormat datef = new SimpleDateFormat("HH.mm");
                Calendar ccc = Calendar.getInstance();
                ccc.set(Calendar.YEAR,1970);
                ccc.set(Calendar.MONTH,0);
                ccc.set(Calendar.DAY_OF_MONTH,1);
                Date horaActual = ccc.getTime();
                
                Calendar cccccc = Calendar.getInstance();
                cccccc.set(Calendar.YEAR,1970);
                cccccc.set(Calendar.MONTH,0);
                cccccc.set(Calendar.DAY_OF_MONTH,1);
                horaActual=ccc.getTime();

                hora = datef.format(horaActual);
                String abiertoooo = datef.format(Principal.abierto);
                String cerradooooo = datef.format(Principal.cerrado);
                System.out.println(hora);
                System.out.println(abiertoooo + cerradooooo);
                System.out.println("antes de abierto? "+(Principal.abierto.compareTo(horaActual)>0));
                System.out.println("despues de cerrado? "+(Principal.cerrado.compareTo(horaActual)<0));
                System.out.println("Ho yes" + horaActual);
                System.out.println("abierto cerrado a las "+Principal.abierto+Principal.cerrado);
                
            if(Principal.abierto.compareTo(horaActual)>0){
                JOptionPane.showMessageDialog(null, "Parqueadero por abrir","Error!", JOptionPane.WARNING_MESSAGE);
            }
            else if (Principal.cerrado.compareTo(horaActual)<0){
                JOptionPane.showMessageDialog(null, "Parqueadero ya cerro","Error!", JOptionPane.WARNING_MESSAGE);
            }
            else{
                try {
            
           //inicio comparativo campos blancos
            if(Principal.Parqueaderos.buscarPlacaF(tfPlaca.getText()) || Principal.ColaDeCarros.buscarPlacaCola(tfPlaca.getText())){
                
                if(Principal.Parqueaderos.buscarPlacaF(tfPlaca.getText())){
                    JOptionPane.showMessageDialog(null, "El vehiculo se encuentra actualmente parqueado en el parqueadero");
                }else{
                    JOptionPane.showMessageDialog(null, "El vehiculo se encuentra actualmente en la cola de espera");
                }
                
            }else if(rbAuto.isSelected() && (tfPlaca.getText().length()<8 || tfPlaca.getText().length()>8)){
                    if(tfPlaca.getText().length()<8){
                    JOptionPane.showMessageDialog(null, "Placa muy corta, formato: ABC-1234");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Placa muy larga, formato: ABC-1234");
                    }
                
            }
            else if(rbMoto.isSelected()&&(tfPlaca.getText().length()<6 || tfPlaca.getText().length()>6)){
                    if(tfPlaca.getText().length()<6){
                    JOptionPane.showMessageDialog(null, "Placa muy corta, formato: AB123C");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Placa muy larga, formato: AB123C");
                    }
            }
            else{
                String clasevehiculo = "";
                if (rbAuto.isSelected()) {
                    clasevehiculo = "Automovil";
                }
                if (rbMoto.isSelected()) {
                    clasevehiculo = "Motocicleta";
                }
                //Hora de entrada
                DateFormat dateForma = new SimpleDateFormat("HH.mm");
                Calendar ca = Calendar.getInstance();
                Date horaEntrada = ca.getTime();
                hora = dateForma.format(horaEntrada);
                //Fecha de entrada
                DateFormat dateForm = new SimpleDateFormat("dd-MM-yyyy");
                Calendar c = Calendar.getInstance();
                Date fechaEntrada = c.getTime();
                fecha = dateForm.format(fechaEntrada);
                
                if(tfPropietario.getText().compareTo("")==0 || tfPropietario1.getText().compareTo("")==0 || tfPlaca.getText().compareTo("")==0){
                JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos");
                }else{
                Principal.ColaDeCarros.insertar(new Vehiculo(tfPlaca.getText(),clasevehiculo,horaEntrada,new Persona(tfPropietario.getText(),tfPropietario1.getText())));
                JOptionPane.showMessageDialog(null, "El vehiculo se registro exitosamente");
                if(Principal.Parqueaderos.hayDisponible() && Principal.ColaDeCarros.esVacia()==false){                      
                    try { 
                        Principal.Parqueaderos.parquear(Principal.ColaDeCarros.atender());
                    } catch (Exception ex) {
                        Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                                 System.out.println("Se ha atendido un vehiculo");
                }else{
                    System.out.println("No hay lugares para parquear");
                }
                
                //inicio creacion de txt
       
                String titulo = "Ticket "+tfPlaca.getText()+" "+hora+".txt";
                 try {

                     PrintWriter writer = new PrintWriter(titulo,"UTF-8");
                     writer.println("                SECUREPARK");
                     writer.println();
                     writer.println("                   Ticket");
                     writer.println();
                     writer.println("Hora: "+hora+"        Fecha: "+fecha);
                     writer.println();
                     writer.println();
                     writer.println("Nombre: "+tfPropietario.getText());
                     writer.println("Apellido: "+tfPropietario1.getText());
                     writer.println();
                     writer.println(clasevehiculo);
                     writer.println("Placa: "+tfPlaca.getText());
                     writer.println();
                     writer.println();
                     writer.println("Por favor guarde este ticket");
                     writer.println("La multa por la perdida de este ticket es de 15 USD");
                     writer.close();

                 } catch (FileNotFoundException ex) {
                     Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (UnsupportedEncodingException ex) {
                     Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 //Inicio para abrir archivo txt
                 try {

                     File objetofile = new File (titulo);
                     Desktop.getDesktop().open(objetofile);

                  }catch (IOException ex) {

                     System.out.println(ex);

                 }
                
            }
            }//fin comparacion si estan vacios los campos
            
           
            //Principal.ColaDeCarros.insertar(new Vehiculo(tfPlaca.getText(),clasevehiculo,new Persona(tfPropietario.getText(),tfPropietario1.getText(),hora,fechaEntrada)));
            
        }catch (Exception ex) {
            Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
            
          
        
       
       
    }//GEN-LAST:event_button1ActionPerformed

    private void tfPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPropietarioActionPerformed

    private void tfPropietario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPropietario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPropietario1ActionPerformed

    private void rbMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMotoActionPerformed
        // TODO add your handling code here:
        jLabel2.setText("Placa Motocicleta");
    }//GEN-LAST:event_rbMotoActionPerformed

    private void rbAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAutoActionPerformed
        // TODO add your handling code here:
                jLabel2.setText("Placa Auto");
    }//GEN-LAST:event_rbAutoActionPerformed

    private void tfPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPlacaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbAuto;
    private javax.swing.JRadioButton rbMoto;
    private javax.swing.JTextField tfPlaca;
    private javax.swing.JTextField tfPropietario;
    private javax.swing.JTextField tfPropietario1;
    // End of variables declaration//GEN-END:variables
}
