/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Desktop;
import java.io.BufferedWriter;
import java.io.File;

import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import parqueadero_proyecto.*;
/**
 *
 * @author Usuario
 */
public class PanelRetirarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form PanelRetirarVehiculo
     */
    public PanelRetirarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Rplaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Retirar = new javax.swing.JButton();
        vp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        he = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hs = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Modulo Salida de Vehiculos del Parqueadero");

        Retirar.setBackground(new java.awt.Color(255, 51, 0));
        Retirar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Retirar.setForeground(new java.awt.Color(255, 255, 255));
        Retirar.setText("Retirar");
        Retirar.setAutoscrolls(true);
        Retirar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingrese la placa ");

        jLabel3.setText("Valor a pagar: ");

        jLabel4.setText("Hora Entrada:");

        jLabel5.setText("Hora Salida: ");

        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });

        jLabel6.setText("Tiempo Ocupado (min):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(Rplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(54, 54, 54))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hs, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vp, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(he)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(Retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hs, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(he, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vp, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarActionPerformed
        // TODO add your handling code here:
        
        if(Principal.Parqueaderos.buscarPlacaF(Rplaca.getText())){
            
            String horaSalida="";
            String horaEntrada="";
            String fecha = "";
            DateFormat dateForm = new SimpleDateFormat("dd-MM-yyyy");
            Calendar c = Calendar.getInstance();
            Date fechaEntrada = c.getTime();
            fecha = dateForm.format(fechaEntrada);
            //int min=0;
            DateFormat dateForma = new SimpleDateFormat("HH.mm");
            Calendar ca = Calendar.getInstance();
            Date horS = ca.getTime();
            horaSalida = dateForma.format(horS);
            hs.setText(horaSalida);
            horaEntrada=dateForma.format(Principal.Parqueaderos.buscarHoraEntrada(Rplaca.getText()));
            Principal.Parqueaderos.imprimir();
            he.setText(horaEntrada);
            int min=Principal.Parqueaderos.calcularTiempo(Rplaca.getText(),horS);
            to.setText(String.valueOf(min));
            Tarifa ta0=Principal.tarifasAuto.get(0);
            Tarifa ta1=Principal.tarifasAuto.get(1);
            Tarifa ta2=Principal.tarifasAuto.get(2);
            Tarifa ta3=Principal.tarifasAuto.get(3);
            Tarifa tm0=Principal.tarifasMoto.get(0);
            Tarifa tm1=Principal.tarifasMoto.get(1);
            Tarifa tm2=Principal.tarifasMoto.get(2);
            Tarifa tm3=Principal.tarifasMoto.get(3);
            
            vp.setText(String.valueOf(Principal.Parqueaderos.valorPagar(Rplaca.getText(),min,ta0,ta1,ta2,ta3,tm0,tm1,tm2,tm3)));
            
       String nombre = Principal.Parqueaderos.buscarNombre(Rplaca.getText());
        String apellido = Principal.Parqueaderos.buscarApellido(Rplaca.getText());	
        String tipo = Principal.Parqueaderos.buscarTipo(Rplaca.getText());
        Double valor = Principal.Parqueaderos.valorPagar(Rplaca.getText(),min,ta0,ta1,ta2,ta3,tm0,tm1,tm2,tm3);
            Recibo recibo =new Recibo(horaEntrada,horaSalida,fecha,Rplaca.getText(),Principal.Parqueaderos.buscarPlaca(Rplaca.getText()).getPersona().getNombre(),Principal.Parqueaderos.buscarPlaca(Rplaca.getText()).getPersona().getApellido(),Principal.Parqueaderos.buscarPlaca(Rplaca.getText()).getTipo(),valor);
            
            //Inicio Recibo
                String titulo = "Recibo "+Rplaca.getText()+" "+horaSalida+".txt";
                try {

                     PrintWriter writer = new PrintWriter(titulo,"UTF-8");
                     writer.println("                SECUREPARK");
                     writer.println();
                     writer.println("                   RECIBO");
                     writer.println();
                     writer.println("Fecha:"+recibo.getFecha());
                     writer.println("Hora Entrada: "+recibo.getHoraEntrada()+"        Hora Salida: "+recibo.getHoraDeSalida());
                     writer.println();
                     writer.println();
                     writer.println("Nombre: "+recibo.getNombre());
                     writer.println("Apellido: "+recibo.getApellido());
                     writer.println();
                     writer.println("Tipo de Vehículo: "+recibo.getTipoVehiculo());
                     writer.println("Placa: "+Rplaca.getText());
                     writer.println("Valor a pagar: "+recibo.getTotal());
                     writer.println();
                     writer.println();
                     writer.println("Gracias por Preferirnos");
                     writer.close();

                 } catch (FileNotFoundException ex) {
                     Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                 } catch (UnsupportedEncodingException ex) {
                     Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                 }
                 //Inicio para abrir archivo txt
                 try {

                     File objetofile = new File (titulo);
                     Desktop.getDesktop().open(objetofile);

                  }catch (IOException ex) {

                     System.out.println(ex);

                 }
                
               Principal.Parqueaderos.desparquear(Rplaca.getText());
               JOptionPane.showMessageDialog(null, "El vehiculo se retiro exitosamente");


            
            
            
            
            
            
            if(Principal.Parqueaderos.hayDisponible() && Principal.ColaDeCarros.esVacia()==false){                      
                    try { 
                        Principal.Parqueaderos.parquear(Principal.ColaDeCarros.atender());
                        System.out.println("Se ha atendido un vehiculo");
                    } catch (Exception ex) {
                        Logger.getLogger(PanelIngresarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                                 
            }
            BufferedWriter bw = null;	
        FileWriter fw = null;	
    try {	
        	
        File file = new File("TABLA.txt");	
        	
        if (!file.exists()) {	
            file.createNewFile();	
        }	
        	
        fw = new FileWriter(file.getAbsoluteFile(), true);	
        bw = new BufferedWriter(fw); 	
        
        
        
        bw.write("\n"+nombre+	
                "\t\t"+apellido+	
                "\t\t"+tipo+	
                "\t\t"+Rplaca.getText()+	
                "\t\t"+horaEntrada+	
                "\t\t"+horaSalida+"\t\t$"+valor);	
        	
        	
    } catch (IOException e) {	
        e.printStackTrace();	
    } finally {	
        try {	
            //Cierra instancias de FileWriter y BufferedWriter	
            if (bw != null)	
                bw.close();	
            if (fw != null)	
                fw.close();	
        } catch (IOException ex) {	
            ex.printStackTrace();	
        }	
    }
        }else{
            JOptionPane.showMessageDialog(null, "No se encontró el vehículo");
        }
        
    }//GEN-LAST:event_RetirarActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retirar;
    private javax.swing.JTextField Rplaca;
    private javax.swing.JTextField he;
    private javax.swing.JTextField hs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField to;
    private javax.swing.JTextField vp;
    // End of variables declaration//GEN-END:variables
}
