/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import parqueadero_proyecto.Tarifa;

/**
 *
 * @author Usuario
 */
public class Tarifas extends javax.swing.JFrame {

    /**
     * Creates new form Tarifas
     */
    public Tarifas() {
        initComponents();
        setLocationRelativeTo(null);
        List <Tarifa> tarifas = new ArrayList<>();
        tarifas.add(new Tarifa("Menos de 25",0.25));
        tarifas.add(new Tarifa("Entre 25 min y 1 hora",0.5));
        tarifas.add(new Tarifa("Entre 1 hora y 5 horas ",2.00));
        tarifas.add(new Tarifa("Más de 5 horas",7.00));
        //Iterator<Tarifa> it = tarifas.iterator();
        String t="";
        for(int i=0; i<tarifas.size();i++){
            t=t+tarifas.get(i)+"\n";
            
        }
        Tarifas.setText(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tarifas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Tarifas.setColumns(20);
        Tarifas.setRows(5);
        jScrollPane1.setViewportView(Tarifas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Tarifas;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
